# List of dependecies for CSI attacher

[[constraint]]
  name = "github.com/container-storage-interface/spec"
  version = "~0.3.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

#[[constraint]]
#  name = "github.com/golang/mock"
#  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/kubernetes-csi/csi-test"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.9.2"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.0"

[[override]]
  name = "github.com/json-iterator/go"
  version = "1.1.4"

[[constraint]]
  name = "github.com/kubernetes-csi/csi-lib-utils"
  version = "0.2.0"
