# List of dependecies for CSI attacher

[[constraint]]
  name = "github.com/container-storage-interface/spec"
  version = "=1.1.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"

[[constraint]]
  name = "github.com/kubernetes-csi/csi-test"
  version = "2.0"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.9.2"

[[override]]
  name = "github.com/json-iterator/go"
  version = "1.1.4"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.14.0"

[[constraint]]
  name = "k8s.io/csi-translation-lib"
  version = "kubernetes-1.14.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.14.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.14.0"

[[constraint]]
  name = "github.com/kubernetes-csi/csi-lib-utils"
  version = ">=0.6.1"

[prune]
   non-go = true
   go-tests = true
   unused-packages = true

